name: mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.3.0
  carousel_slider: ^5.0.0
  flutter_widget_from_html: ^0.15.1
  dio: ^5.5.0+1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  device_info_plus: ^10.1.1
  cached_network_image: ^3.4.0
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logo/
    - assets/icon/
    - assets/dummy/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 19
  remove_alpha_ios: true
  image_path: "assets/logo/app-logo.png"
